// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtUpfNI2T_wH8T03vJsB0B3tyayql69rU',
    appId: '1:214135885758:web:ef30546265283fe742b3ef',
    messagingSenderId: '214135885758',
    projectId: 'peto-627d1',
    authDomain: 'peto-627d1.firebaseapp.com',
    storageBucket: 'peto-627d1.appspot.com',
    measurementId: 'G-R136GFM4ZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_xU-nSk2DKjN7luAju9oTggcSbFwDWwE',
    appId: '1:214135885758:android:ef78e480586c3a7f42b3ef',
    messagingSenderId: '214135885758',
    projectId: 'peto-627d1',
    storageBucket: 'peto-627d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvjdmd7GYxWN4YkuzGDRz8BS59NgIoZOQ',
    appId: '1:214135885758:ios:d7ca4730a993270942b3ef',
    messagingSenderId: '214135885758',
    projectId: 'peto-627d1',
    storageBucket: 'peto-627d1.appspot.com',
    iosClientId: '214135885758-976v5gn6fg42b6q7kkpvh51gts6uchvi.apps.googleusercontent.com',
    iosBundleId: 'com.example.peto',
  );
}
